import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "plant villa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        
        <header className="bg-[#F4F9F4] backdrop-blur-md border-b border-outline-variant/30">
          <div className="min-h-screen">
            
            
            
            <main>
              {children} 
            </main>
            
            

          </div>
        </header>
        
      </body>
    </html>
  );
}