import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "plant villa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <header className="bg-white/80 backdrop-blur-md border-b border-outline-variant/30">
        <div className="max-w-[1280px] mx-auto px-6 py-4 flex justify-between items-center ">

          <Navbar/>
        </div>
        </header>
        
        {children}</body>
    </html>
  );
}
