import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from '@/components/Hero';
import TrustBar from '@/components/TrustBar';
import Categories from '@/components/Categories';
import ProductShowcase from '@/components/ProductShowcase';
import Newsletter from '@/components/Newsletter';
import Footer from '@/components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "plant villa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <header className="bg-[#F4F9F4] backdrop-blur-md border-b border-outline-variant/30  ">
        <div className=" min-h-screen">

          <Navbar/>
          <main >
          
        <Hero />
        <TrustBar />
        <Categories />
        <ProductShowcase />
        <Newsletter />
        
      </main>
      <Footer/>

        </div>
        </header>
        
        {children}</body>
    </html>
  );
}
